Document: qmc2
Title: Debian qmc2 Manual
Author: <insert document author here>
Abstract: This manual describes what qmc2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qmc2/qmc2.sgml.gz

Format: postscript
Files: /usr/share/doc/qmc2/qmc2.ps.gz

Format: text
Files: /usr/share/doc/qmc2/qmc2.text.gz

Format: HTML
Index: /usr/share/doc/qmc2/html/index.html
Files: /usr/share/doc/qmc2/html/*.html
