name: CI (Windows)

on:
  push:
  pull_request:

env:
  SDL_VERSION: 2.30.3

jobs:
  build:

    runs-on: windows-2019

    steps:
      - name: Download Qt
        uses: jurplel/install-qt-action@v3
        with:
          version:      5.15.2
          host:         windows
          target:       desktop
          arch:         win64_msvc2019_64
          modules:      qtwebengine
          archives:     qtbase qtdeclarative qtlocation qtmultimedia qtsvg qttools qtwebchannel qtwinextras qtxmlpatterns
          setup-python: false
          cache: true
      - name: Download SDL
        run: |
          Invoke-WebRequest "https://github.com/libsdl-org/SDL/releases/download/release-$env:SDL_VERSION/SDL2-devel-$env:SDL_VERSION-VC.zip" -OutFile ${{ runner.workspace }}\SDL2.zip
          Expand-Archive ${{ runner.workspace }}\SDL2.zip -DestinationPath ${{ runner.workspace }}
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: make
          path-type: inherit
      - uses: actions/checkout@v4
      - name: Configure
        env:
          MKSPEC: win32-msvc
          FORCE_MINGW: 0
          ARCH: Windows
          SDL: 2
          SDL_LIBS: 'LIBS+="../SDL2-${SDL_VERSION}/lib/x64/SDL2.lib ../SDL2-${SDL_VERSION}/lib/x64/SDL2main.lib"'
          SDL_INCLUDEPATH: 'INCLUDEPATH+=../SDL2-${SDL_VERSION}/include'
        shell: msys2 {0}
        run: make -j4 configure
      - name: Build
        run: nmake /f Makefile.qmake.release
      - name: Deploy
        run: |
          windeployqt release\qmc2-mame.exe
          Copy-Item ${{ runner.workspace }}\SDL2-$env:SDL_VERSION\lib\x64\SDL2.dll  release
      - uses: actions/upload-artifact@v4
        with:
          name: qmc2-windows-2019-${{ github.sha }}
          path: |
            release

